feat: add set_xinitrc()

diff --git a/mhym b/mhym
--- a/mhym
+++ b/mhym
@@ -38,6 +38,26 @@ POST_INSTALL_SYSTEM_PACAGES=(
 #----------------------------------------------
 
 
+
+#------------XRESOURCES-SETTING----------------------
+#settings for .Xresources
+
+#set this to true ,if you want to overwrite
+#.Xresources
+OVERWRITE_XRESOURCES=false
+
+#set this to true, if you want to merge
+# .Xresources with current settings
+MERGE_XRESOURCES=false
+
+#path to .Xresources file
+# will only be read if either OVERWRITE_XRESOURCES
+# or MERGE_XRESOURCES is true
+DOTXRESOURCES_PATH=""
+
+#----------------------------------------------------
+
+
 #--------------WALLPAPER-SETTING------------------
 # utility for setting wallpaper
 BG_UTIL="feh"
@@ -51,6 +71,13 @@ UTIL_CMD="--bg-scale "
 BACKGROUND_PATH=""
 #-------------------------------------------------
 
+
+
+#---------------STATUS-BAR-SETTING----------------
+# settings for dwm status-bar
+
+
+#-------------------------------------------------
 
 
 #---------------MISCELLANEOUS-------------------
@@ -124,6 +151,9 @@ sync_apt_repo(){
     info "Syncing apt with remote repos" "log"
     info "Invoking su user..."
     su
+    if [[ "$?" -ne "0" ]];then
+        error "error logging to su user, quitting" "exit-after"
+    fi
     yes | apt update > /dev/null
     if [[ "$?" -ne "0" ]]; then
         error "\`apt update\` failed, possibly due to: "
@@ -145,7 +175,10 @@ install_n_configure_sudo(){
     printf "no\n"
     info "Installing sudo for $user_name" "log"
     info "Invoking su user" "log"
-    su
+    su > /dev/null
+    if [[ "$?" -ne "0" ]];then
+        error "error logging to su user, quitting" "exit-after"
+    fi
     apt install sudo  > /dev/null
     if [[ "$?" -ne "0" ]]; then
         error "error occured while installing sudo. resolve manually and continue, quitting" "quit-after"
@@ -258,15 +291,31 @@ install_n_configure_dwm(){
 }
 
 
-set_wallpaper(){
+set_xinitrc(){
     if [[ -z "$BACKGROUND_PATH" ]];then
-        out=$(readline_prompt "path to background file: ")
+        out=$(readline_prompt "path to wallpaper file: ")
         BACKGROUND_PATH=$out
     fi
-    $BG_UTIL $UTIL_CMD $BACKGROUND_PATH > /dev/null
-    if [[ "$?" -ne 0 ]];then
-        warning "Wallpaper could not be set. continuing!"
+    
+    local xresources_cmd=""
+    if [[ $OVERWRITE_XRESOURCES = true ]]; then
+        if [[ -z $DOTXRESOURCES_PATH ]];then
+            error "need path for .Xresources. quitting!" "exit-after"
+        fi
+        xresources_cmd="xrdb $DOTXRESOURCES_PATH"
+    elif [[ $MERGE_XRESOURCES = true ]]; then
+        if [[ -z $DOTXRESOURCES_PATH ]];then
+            error "need path for .Xresources. quitting!" "exit-after"
+        fi 
+        xresources_cmd="xrdb -merge $DOTXRESOURCES_PATH" 
     fi
+
+    cat > "$HOME/.xinitrc" << EOT
+# .xinitrc generated by mhym
+$xresources_cmd
+$BG_UTIL $UTIL_CMD $BACKGROUND_PATH
+exec dwm
+EOT
 }
 
 
@@ -274,7 +323,7 @@ if [ -d '$HOME/.MHYM_RESUME_STATE' ]; then
     info "Resuming state after \`sudo\` install..." "log"
     install_dwm_deps
     install_n_configure_dwm
-    set_wallpaper
+    set_xinitrc
     exit 0
 fi
 
